# Generated by Django 4.2.1 on 2023-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_subyollanma_yollanma_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='chegirma',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
